name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    name: CI

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.18.2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Init pnpm (latest)
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Node.js (v${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type-checking
        run: pnpm run type-check

      - name: Run Biome CI
        run: pnpm run lint

      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: |
            docs/**/*.md
            #node_modules/
            #**/node_modules/**

      - name: Run unit & integration tests
        run: pnpm run test

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: packages/repository
