name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: CI

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.18.2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Init Bun
        uses: oven-sh/setup-bun@v1

      - name: Use Node.js (v${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: bun install

      - name: Type-checking
        run: bun run type-check

      - name: Try to build it
        run: bun run build

      - name: Run Biome CI
        run: bun run lint

      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: |
            docs/**/*.md
            #node_modules/
            #**/node_modules/**

      - name: Run unit & integration tests
        run: bun run test

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: packages/repository
