name: Unit & integration tests

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    name: Testing

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    strategy:
      matrix:
        node-version: [18.18.2]
        package: ["repository"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Init pnpm (latest)
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Node.js (v${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit & integration tests
        run: pnpm run test

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: packages/${{ matrix.package }}
